# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’
 # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

target 'ZHA-DouYu-Swift3.0' do
 
pod "SnapKit"                       	#Swift中 的自动布局的第三方库
pod "Kingfisher"                    	#Swift中类似oc强大图片缓存处理的库SDWebImage
pod "SVProgressHUD"                	#oc显示提示消息的
pod 'Alamofire', '~> 4.2.0'		#类似于oc中的AFNetWorking
pod "SwiftyJSON"                    	#在swift中使用SwiftyJSON可以很方便的处理JSON数据
pod 'BarrageRenderer', '~> 1.8.0'	#oc中的弹幕
pod 'MJRefresh', '~> 3.1.1'         	#oc下拉刷新
pod 'LFLiveKit', '~> 2.3'           	#oc美颜相机和直播推流
pod 'MBProgressHUD', '~> 0.9.2'     	#oc弹窗提示框

end
